In [97]:
import numpy as np
#y = x1**2+x2**2+x3**2
y1 =np.array([[0,1,0,0],[0,0,1,0],[1,0,0,0],[0,0,0,1]])#,[0,0,1],[1,0,0]
x1 =np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])#,[4,5,6],[7,8,9]
print(x1.shape)
w1 =np.random.rand(100,3)
print(w1.shape)
a1 =np.random.rand(3,100)
trans =np.random.rand(3,4)
# wx=w1*x1
# c =np.cos(wx)
# print(c.shape)
# pre =np.diag(a@c)
# print(pre)
for i in range(3000):
    for x,y in zip(x1,y1):
        wx=w1*x
        c =np.cos(wx)+np.sin(wx)
        pre =np.diag(a1@c)
        final =pre@trans
        w1 = w1+1e-3*a1.T*x*((final-y)@trans.T)*np.sin(w1)-1e-3*a1.T*x*((final-y)@trans.T)*np.cos(w1)
        a1 = a1-1e-3*(final-y)@trans.T@c.T
        trans = trans -1e-5*((np.ones((1,3))*pre).T)@(np.ones((1,4))*(final-y))
        if i==2999:
            print(final)

(4, 3)
(100, 3)
[-0.05100436  0.96337688  0.09816123 -0.04196594]
[0.23327338 0.07609482 0.54392023 0.43215846]
[ 0.88062004 -0.04328414  0.23473668 -0.21693254]
[-0.21980826 -0.07138462  0.43080202  0.58211647]


In [184]:
y1 =np.array([[0.1,0.2,0.3],[0.4,0.5,0.6],[0.7,0.8,0.9],[0.10,0.11,0.12]])#,[0,0,1],[1,0,0]
x1 =np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])#,[4,5,6],[7,8,9]
print(x1.shape)
w1 =np.random.rand(100,3)
print(w1.shape)
a1 =np.random.rand(3,100)
# wx=w1*x1
# c =np.cos(wx)
# print(c.shape)
# pre =np.diag(a@c)
# print(pre)
for i in range(1000):
    for x,y in zip(x1,y1):
        wx=w1*x
        c =np.cos(wx)+np.sin(wx)
        pre =np.diag(a1@c)
        w1 = w1+1e-3*a1.T*x*(pre-y)*np.sin(w1)-1e-3*a1.T*x*(pre-y)*np.cos(w1)
        a1 = a1-1e-3*(pre-y)@c.T
        if i==999:
            print(pre)

(4, 3)
(100, 3)
[0.09998866 0.20001097 0.30000222]
[0.39999996 0.49999815 0.59999897]
[0.70000053 0.80000077 0.90000121]
[0.10000077 0.10999872 0.11999926]


In [95]:
print((final-y)@trans.T)

[-1.89836701e-05  4.14324381e-05  8.19755844e-06]


In [272]:
def broad(a,b):
    re=a
    for i in range(a.shape[0]):
        re[i,:,:]=a[i]*b[i]
    return re

In [321]:
import torch
#y = x1**2+x2**2+x3**2
y = torch.Tensor([[0,1,0],[0,0,1]])#,[0,0,1],[1,0,0]
x1 =torch.Tensor([[1,2,3],[4,5,6]])#,[4,5,6],[7,8,9]
print(x1.shape)
w1 =torch.rand(2,100,3)
print(w1.shape)
a =torch.rand(2,3,100)
wx=broad(w1,x1)
c =torch.cos(wx)
print(c.shape)
pre =torch.ones_like(y)
for i in range(2):
    pre[i]=torch.diag(a[i,:,:]@c[i,:,])
print(pre)
for l in range(100):
    for i in range(2):
        w1[i] = w1[i]+0.01*a[i].T*x1[i]*(pre[i]-y[i])*torch.sin(w1[i])
        a[i] = a[i]-0.01*(pre[i]-y[i])@c[i].T
#         for j in range(3):
#             a[i,j,:] = a[i,j,:]-0.001*c[i,:,j]*(pre[i,j]-y[i,j])
    wx=broad(w1,x1)
    c =torch.cos(wx)
    for i in range(2):
    pre[i]=torch.diag(a[i]@c[i])
    print(pre)


torch.Size([2, 3])
torch.Size([2, 100, 3])
torch.Size([2, 100, 3])
tensor([[ 42.1363,  22.5200,  10.1245],
        [ -9.4454, -11.8877,  -0.3075]])
tensor([[ 1.3948, -8.0447,  2.8303],
        [-1.6969, -1.1930,  1.7092]])
tensor([[-0.4676, -3.7236, -4.4864],
        [-1.0310, -2.7971,  5.5249]])
tensor([[ 0.0638,  5.8453,  1.2331],
        [-2.3763, -1.3614,  1.0587]])
tensor([[ 0.0218, -1.7158, -2.1031],
        [ 1.0882, -1.3653,  5.4188]])
tensor([[-0.1107,  3.9292, -2.0941],
        [-0.8978, -2.6146,  1.1277]])
tensor([[-0.0700,  0.6793, -2.6669],
        [ 2.0215, -3.9022,  0.2968]])
tensor([[-3.4093e-03,  1.4850e+00, -4.5237e+00],
        [ 4.0469e+00, -2.2097e+00,  1.0309e+00]])
tensor([[-0.3620,  1.6729, -1.3558],
        [ 5.5846,  1.8028, -2.0851]])
tensor([[-0.2545,  1.6626,  1.8292],
        [ 1.4478,  2.7655, -0.9911]])
tensor([[-0.0723,  1.9141, -1.1614],
        [ 0.8112,  0.3826,  1.2662]])
tensor([[ 0.0889, -2.5816,  2.1291],
        [ 4.0010, -7.4797,  2.7984]])
ten

In [303]:
print((c@torch.diag_embed(pre1-y)).shape)

torch.Size([2, 100, 3])


In [183]:
y = np.array([[0.1,0.2,0.3],[0.4,0.5,0.6],[0.7,0.8,0.9],[0.10,0.11,0.12]])#3*2
x1 =np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])#
print(x1.shape)
w1 =np.random.rand(3,50)
w2 =np.random.rand(50,3)
print(w1.shape)
out =np.exp(-x1@w1)
pre =out@w2
#print(pre)
for i in range(3000):
    w1 =w1-1e-3*x1.T@((pre-y)@w2.T*(1-out)*out)
    w2 =w2-1e-3*(out.T@(pre-y))
    out =np.sin(x1@w1)
    pre =out@w2
print(pre)

(4, 3)
(3, 50)
[[0.10002904 0.20016345 0.29997384]
 [0.40002731 0.49946569 0.60008134]
 [0.70003528 0.79997819 0.89986682]
 [0.10004819 0.10983307 0.11996625]]
